export const SELECT_EMPLOYEE = "SELECT_EMPLOYEE";
export const UPDATE_INFO_EMPLOYEE = "UPDATE_INFO_EMPLOYEE";
export const CREATE_NEW_EMPLOYEE = "CREATE_NEW_EMPLOYEE";
export const DELETE_EMPLOYEES = "DELETE_EMPLOYYES";
